services:
  lnkr:
    image: ${REGISTRY_URL}lnkr:latest
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - nginx
      - default
    environment:
      REDIS_HOSTNAME: redis
      POSTGRES: postgres://postgres@postgres/postgres

  redis:
    image: redis:8-alpine
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - lnkr:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  lnkr:

networks:
  nginx:
    name: nginx
    external: true
