services:
  redis:
    extends:
      file: docker-compose.yaml
      service: redis
    network_mode: host

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    network_mode: host
