services:
  lnkr:
    image: registry.nyzhnyk.dev/lnkr:latest
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - nginx
      - default
    environment:
      REDIS_HOSTNAME: redis
      POSTGRES: postgres://postgres@postgres/postgres

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - default

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  nginx:
    name: nginx
    external: true
  default:
